version: 1.0.{build}
clone_depth: 1
skip_tags: true
environment:
  JAVA_HOME: C:\Program Files\Java\jdk17
cache:
- C:\Users\appveyor\.gradle\caches\fabric-loom
- C:\Users\appveyor\.gradle\caches\modules-2\
build_script:
- cmd: gradlew build
test: off
artifacts:
- path: .\build\libs\BorderRemover-1.0.9.jar
  name: BorderRemover-1.0.9.jar
- path: .\build\devlibs\BorderRemover-1.0.9-sources.jar
  name: BorderRemover-1.0.9-sources.jar
deploy:
- provider: GitHub
  tag: 1.0.9
  auth_token:
    secure: EEbZ2OGaIPcjhGpQGzfE80TbrG14UiTPGNnQjMIKD5wzrYPQ4Kyhb3qLzMNahL1I
  repository: PercyDan54/BorderRemover
  artifact: BorderRemover-1.0.9.jar, BorderRemover-1.0.9-sources.jar
