version: 1.0.{build}
clone_depth: 1
environment:
  JAVA_HOME: C:\Program Files\Java\jdk16
cache:
- C:\Users\appveyor\.gradle\caches\fabric-loom
- C:\Users\appveyor\.gradle\caches\modules-2\
- .\.gradle
build_script:
- cmd: gradlew build
test: off
artifacts:
- path: .\build\libs\BorderRemover-1.0.2.jar
  name: BorderRemover-1.0.2.jar
- path: .\build\libs\BorderRemover-1.0.2-sources-dev.jar
  name: BorderRemover-1.0.2-sources-dev.jar
deploy:
- provider: GitHub
  tag: 1.0.2
  auth_token:
    secure: wBUeC7f0SGZTu01Bl50RTSas9yizhxdAeqofugDSTpOoZFXOyzvP+X2OOAnaqIWz
  repository: PercyDan54/BorderRemover
  artifact: BorderRemover-1.0.2.jar, BorderRemover-1.0.2-sources-dev.jar
